ARG MAIN_PACKAGES="binutils coreutils-single gcc gcc-c++ glibc-devel make"

ARG NEWROOT=/new-root-fs
ARG DNF_CACHE=/tmp/dnf-cache
ARG DNF_FLAGS="-y \
      --use-host-config \
      --nodocs \
      --setopt=install_weak_deps=False \
      --setopt=cachedir=${DNF_CACHE} \
      --setopt=system_cachedir=${DNF_CACHE} \
      --setopt=logdir=${DNF_CACHE}"

FROM registry.fedoraproject.org/fedora:rawhide AS builder
ARG NEWROOT
ARG DNF_CACHE
ARG DNF_FLAGS
ARG MAIN_PACKAGES

RUN mkdir -p ${NEWROOT} ${DNF_CACHE}

RUN dnf --installroot=${NEWROOT} ${DNF_FLAGS} install filesystem
RUN dnf --installroot=${NEWROOT} ${DNF_FLAGS} install ${MAIN_PACKAGES}

RUN rm -rf \
      ${NEWROOT}/usr/share/licenses \
      ${NEWROOT}/usr/share/locale \
      ${NEWROOT}/var/cache/* \
      ${NEWROOT}/etc/machine-id \
      ${NEWROOT}/etc/{group,gshadow,passwd,shadow}-

FROM scratch
ARG NEWROOT
COPY --from=builder ${NEWROOT} /

LABEL name="hummingbird/c"
LABEL summary="C/C++ development toolchain based on GCC"
LABEL description="Provides the GNU Compiler Collection (GCC) with C and C++ support, GNU Make, and the GNU C Library headers. Suitable for compiling C and C++ applications in multi-stage container builds."
LABEL url="https://gcc.gnu.org"
LABEL maintainer="Project Hummingbird / Red Hat"
LABEL vendor="Red Hat, Inc."
LABEL io.hummingbird-project.repository="c"
LABEL io.hummingbird-project.stream="latest"
LABEL io.hummingbird-project.application-category="Programming Languages & Runtimes"
LABEL io.hummingbird-project.variant="default"
LABEL io.hummingbird-project.variant.description="Standard production image"

ENV CC=gcc \
    CXX=g++

CMD ["bash"]

USER root
